// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package device

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DeviceClient is the client API for Device service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DeviceClient interface {
	Connect(ctx context.Context, in *ConnectReq, opts ...grpc.CallOption) (*ConnectReply, error)
	ReConnect(ctx context.Context, in *ReConnectReq, opts ...grpc.CallOption) (*ReConnectReply, error)
	DisConnect(ctx context.Context, in *DisConnectReq, opts ...grpc.CallOption) (*DisConnectReply, error)
	Focus(ctx context.Context, in *FocusReq, opts ...grpc.CallOption) (*FocusReply, error)
	Input(ctx context.Context, opts ...grpc.CallOption) (Device_InputClient, error)
	Output(ctx context.Context, in *OutputReq, opts ...grpc.CallOption) (Device_OutputClient, error)
}

type deviceClient struct {
	cc grpc.ClientConnInterface
}

func NewDeviceClient(cc grpc.ClientConnInterface) DeviceClient {
	return &deviceClient{cc}
}

func (c *deviceClient) Connect(ctx context.Context, in *ConnectReq, opts ...grpc.CallOption) (*ConnectReply, error) {
	out := new(ConnectReply)
	err := c.cc.Invoke(ctx, "/device.Device/Connect", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceClient) ReConnect(ctx context.Context, in *ReConnectReq, opts ...grpc.CallOption) (*ReConnectReply, error) {
	out := new(ReConnectReply)
	err := c.cc.Invoke(ctx, "/device.Device/ReConnect", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceClient) DisConnect(ctx context.Context, in *DisConnectReq, opts ...grpc.CallOption) (*DisConnectReply, error) {
	out := new(DisConnectReply)
	err := c.cc.Invoke(ctx, "/device.Device/DisConnect", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceClient) Focus(ctx context.Context, in *FocusReq, opts ...grpc.CallOption) (*FocusReply, error) {
	out := new(FocusReply)
	err := c.cc.Invoke(ctx, "/device.Device/Focus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceClient) Input(ctx context.Context, opts ...grpc.CallOption) (Device_InputClient, error) {
	stream, err := c.cc.NewStream(ctx, &Device_ServiceDesc.Streams[0], "/device.Device/Input", opts...)
	if err != nil {
		return nil, err
	}
	x := &deviceInputClient{stream}
	return x, nil
}

type Device_InputClient interface {
	Send(*InputReq) error
	CloseAndRecv() (*InputReply, error)
	grpc.ClientStream
}

type deviceInputClient struct {
	grpc.ClientStream
}

func (x *deviceInputClient) Send(m *InputReq) error {
	return x.ClientStream.SendMsg(m)
}

func (x *deviceInputClient) CloseAndRecv() (*InputReply, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(InputReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *deviceClient) Output(ctx context.Context, in *OutputReq, opts ...grpc.CallOption) (Device_OutputClient, error) {
	stream, err := c.cc.NewStream(ctx, &Device_ServiceDesc.Streams[1], "/device.Device/Output", opts...)
	if err != nil {
		return nil, err
	}
	x := &deviceOutputClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Device_OutputClient interface {
	Recv() (*OutputReply, error)
	grpc.ClientStream
}

type deviceOutputClient struct {
	grpc.ClientStream
}

func (x *deviceOutputClient) Recv() (*OutputReply, error) {
	m := new(OutputReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// DeviceServer is the server API for Device service.
// All implementations must embed UnimplementedDeviceServer
// for forward compatibility
type DeviceServer interface {
	Connect(context.Context, *ConnectReq) (*ConnectReply, error)
	ReConnect(context.Context, *ReConnectReq) (*ReConnectReply, error)
	DisConnect(context.Context, *DisConnectReq) (*DisConnectReply, error)
	Focus(context.Context, *FocusReq) (*FocusReply, error)
	Input(Device_InputServer) error
	Output(*OutputReq, Device_OutputServer) error
	mustEmbedUnimplementedDeviceServer()
}

// UnimplementedDeviceServer must be embedded to have forward compatible implementations.
type UnimplementedDeviceServer struct {
}

func (UnimplementedDeviceServer) Connect(context.Context, *ConnectReq) (*ConnectReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedDeviceServer) ReConnect(context.Context, *ReConnectReq) (*ReConnectReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReConnect not implemented")
}
func (UnimplementedDeviceServer) DisConnect(context.Context, *DisConnectReq) (*DisConnectReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DisConnect not implemented")
}
func (UnimplementedDeviceServer) Focus(context.Context, *FocusReq) (*FocusReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Focus not implemented")
}
func (UnimplementedDeviceServer) Input(Device_InputServer) error {
	return status.Errorf(codes.Unimplemented, "method Input not implemented")
}
func (UnimplementedDeviceServer) Output(*OutputReq, Device_OutputServer) error {
	return status.Errorf(codes.Unimplemented, "method Output not implemented")
}
func (UnimplementedDeviceServer) mustEmbedUnimplementedDeviceServer() {}

// UnsafeDeviceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DeviceServer will
// result in compilation errors.
type UnsafeDeviceServer interface {
	mustEmbedUnimplementedDeviceServer()
}

func RegisterDeviceServer(s grpc.ServiceRegistrar, srv DeviceServer) {
	s.RegisterService(&Device_ServiceDesc, srv)
}

func _Device_Connect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceServer).Connect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/device.Device/Connect",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceServer).Connect(ctx, req.(*ConnectReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Device_ReConnect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReConnectReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceServer).ReConnect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/device.Device/ReConnect",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceServer).ReConnect(ctx, req.(*ReConnectReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Device_DisConnect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisConnectReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceServer).DisConnect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/device.Device/DisConnect",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceServer).DisConnect(ctx, req.(*DisConnectReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Device_Focus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FocusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceServer).Focus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/device.Device/Focus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceServer).Focus(ctx, req.(*FocusReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Device_Input_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DeviceServer).Input(&deviceInputServer{stream})
}

type Device_InputServer interface {
	SendAndClose(*InputReply) error
	Recv() (*InputReq, error)
	grpc.ServerStream
}

type deviceInputServer struct {
	grpc.ServerStream
}

func (x *deviceInputServer) SendAndClose(m *InputReply) error {
	return x.ServerStream.SendMsg(m)
}

func (x *deviceInputServer) Recv() (*InputReq, error) {
	m := new(InputReq)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Device_Output_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(OutputReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DeviceServer).Output(m, &deviceOutputServer{stream})
}

type Device_OutputServer interface {
	Send(*OutputReply) error
	grpc.ServerStream
}

type deviceOutputServer struct {
	grpc.ServerStream
}

func (x *deviceOutputServer) Send(m *OutputReply) error {
	return x.ServerStream.SendMsg(m)
}

// Device_ServiceDesc is the grpc.ServiceDesc for Device service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Device_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "device.Device",
	HandlerType: (*DeviceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Connect",
			Handler:    _Device_Connect_Handler,
		},
		{
			MethodName: "ReConnect",
			Handler:    _Device_ReConnect_Handler,
		},
		{
			MethodName: "DisConnect",
			Handler:    _Device_DisConnect_Handler,
		},
		{
			MethodName: "Focus",
			Handler:    _Device_Focus_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Input",
			Handler:       _Device_Input_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "Output",
			Handler:       _Device_Output_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "device.proto",
}
