.nh
.TH "IM Protocol Tools" "1" "Jun 2022" "" ""

.SH NAME
.PP
test-doc - 生成Protocol工具参考文档


.SH SYNOPSIS
.PP
\fBtest doc [flags]\fP


.SH DESCRIPTION
.PP
生成Protocol工具参考文档


.SH OPTIONS
.PP
\fB-d\fP, \fB--dir\fP="./"
	文档输出目录

.PP
\fB-f\fP, \fB--format\fP=""
	文档格式

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for doc


.SH SEE ALSO
.PP
\fBtest(1)\fP
